version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "php"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "scalafmt"

[[transformers]]
name = "prettier"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true
